### ISSUE TITLE
Default values -- minimum concept distance

### ISSUE THREAD

**Issue by melvinwevers** [NLeSC/ShiCo#11]
0.7 perhaps?
Would it make sense to make allow the user to change the measure with 2 decimals?

**Comment by c-martinez** [comment]
Also, years in aggregation interval = 5

**Comment by c-martinez** [comment]
Reopening this -- it seems 0.7 most of the time gives no results. Perhaps lower to 0.7.

On a related note -- when no results, perhaps it is nice to show the user an informative message.
