### ISSUE TITLE
Big graphs

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ShiCo#23]
If enough space is given, network graphs become really tall. This can be solved on Texcavator (@mhkuu), but perhaps nice to also fix in ShiCo (if possible).

**Comment by mhkuu** [comment]
I'm solving this in Texcavator by explicitly setting the height for the graphs. I have to do this, because there's a CSS rule that sets the width and height of every `svg.nvd3-svg` to 100%. This overrules the attributes you've currently set.

**Comment by c-martinez** [comment]
Since this is fixed on Texcavator side, can close this issue, right?

**Comment by mhkuu** [comment]
Yes! :+1:
