### ISSUE TITLE
Display the vocabularies themselves

### ISSUE THREAD

**Issue by MacTommyK** [NLeSC/ShiCo#24]
I was showing ShiCo to someone just now, and I realised that what I miss in the interface is, what I always thought of as, the final product: the vocabularies per time period.

In the paper we talk about 5 year periods, and what we aim for in the end is a list of 10 words for every 5 year period.

I think it would be really nice if these lists were indeed displayed in the tool.

I made a really simple mockup screenshot of how I think it might look.
![shico screenshot](https://cloud.githubusercontent.com/assets/13980603/14709742/873e71fc-07d2-11e6-9969-2e36c5f04d79.png)

**Comment by MacTommyK** [comment]
Ca I invite other people, like @melvinwevers, like this?

**Comment by melvinwevers** [comment]
Yes :)

**Comment by c-martinez** [comment]
Nice idea. Couple of points:

 - If a word (say `oorlog`), is present in more than one time period, it should appear in each of them, correct?
 - Is the relative importance (i.e. the width of the bar on the stream graph) important? Should we display the word with the value (e.g. `oorlog (0.54)`)
 - Problem: number of years in period is configurable, meaning that you can end up with a lot of these vocabularies, and they would overlap. So I might not necessarily align them with the axis but add a scroll bar or something... (anyway, that is a detail).

**Comment by MacTommyK** [comment]
1. Yes.
2. Good point. I, for one, would like to see it
3. Yes, this occurred to me as well. I am very much in favor of aligning these lists with the axis in the plot though. That really keeps thing easy to interpret, in my opinion.
But indeed, things might get cluttered.

One, admittedly not very good, answer to this is that having a very low number of years per period isn't a very good idea in the first place.
Or maybe the vocabularies could be collapsible? So, be default you open a couple every so-many periods, so they don't overlap. All the intermediate ones you fold out?
I was actually hoping Carlos would come up with a brilliant solution ;-)

**Comment by MacTommyK** [comment]
As a solution to this 3rd point: why don't we just blow up the graph?
I.e., make it wider, horizontally, so the vocabularies (which are aligned to it ;-) ) do fit.

The user might have to scroll to see everything, but as (s)he just asked for very detailed information, I would argue that only figures.

**Comment by MacTommyK** [comment]
Also, on a related note, I would suggest to make 5 year periods the default (rather than 1 year periods, as is the default now, which pretty much defies the purpose of having an aggregation method at all).

**Comment by c-martinez** [comment]
I was thinking something along those lines. We should be able to align the axis with the vocabularies.

RE 5 year period default -- sure, will add to #11

**Comment by melvinwevers** [comment]
Did you take a look at the other type of d3 viz I sent. With the individual chart lines for each vocabulary word. This might solve many of our problems without too much clutter.

**Comment by MacTommyK** [comment]
@melvinwevers where did you post these other visualisations?

**Comment by melvinwevers** [comment]
I sent an email with the images a week ago or so.

**Comment by c-martinez** [comment]
Haven't added anything yet, sorry @melvinwevers -- will do as soon as possible.

**Comment by melvinwevers** [comment]
No worries, just wanted to double check whether you got the info.
